INSERT INTO public.skill (id, version, label) VALUES (9, 0, 'JAVA');
INSERT INTO public.skill (id, version, label) VALUES (18, 0, 'JAVASCRIPT');
INSERT INTO public.skill (id, version, label) VALUES (27, 0, 'C');
INSERT INTO public.skill (id, version, label) VALUES (36, 0, 'C++');
INSERT INTO public.skill (id, version, label) VALUES (45, 0, 'SWIFT');
INSERT INTO public.skill (id, version, label) VALUES (63, 0, 'HTML');
INSERT INTO public.skill (id, version, label) VALUES (72, 0, 'PHP');
INSERT INTO public.skill (id, version, label) VALUES (81, 0, 'CSS');
INSERT INTO public.skill (id, version, label) VALUES (90, 0, 'VUE JS');
INSERT INTO public.skill (id, version, label) VALUES (99, 0, 'HIBERNATE');
INSERT INTO public.skill (id, version, label) VALUES (117, 0, 'AGILE');
INSERT INTO public.skill (id, version, label) VALUES (135, 0, 'R');
INSERT INTO public.skill (id, version, label) VALUES (144, 0, 'PYTHON');
INSERT INTO public.skill (id, version, label) VALUES (162, 0, 'SYMFONY');
INSERT INTO public.skill (id, version, label) VALUES (171, 0, 'SYMFONY 2');
INSERT INTO public.skill (id, version, label) VALUES (180, 0, 'SQL');
INSERT INTO public.skill (id, version, label) VALUES (189, 0, 'HSQL');
INSERT INTO public.skill (id, version, label) VALUES (108, 1, 'POO');
INSERT INTO public.skill (id, version, label) VALUES (153, 1, 'UML');
INSERT INTO public.skill (id, version, label) VALUES (198, 1, 'SCRUM');
INSERT INTO public.skill (id, version, label) VALUES (54, 1, 'MOBILE');
INSERT INTO public.skill (id, version, label) VALUES (126, 2, 'ANDROID');
INSERT INTO public.skill (id, version, label) VALUES (235, 0, 'BIG DATA');
INSERT INTO public.skill (id, version, label) VALUES (246, 0, 'SPARK');
INSERT INTO public.skill (id, version, label) VALUES (257, 0, 'CONCEPTION');
