
INSERT INTO public.collaborator (id, version, businessunit, defaultpicture, email, firstname, function, isadmin, lastname, password, personnalidnumber) VALUES (nextval('hibernate_sequence'), 0, NULL, 'true', 'john@viseo.com', 'Soline', NULL, 'false', 'John', 123456, 'SOL7897');
INSERT INTO public.collaborator (id, version, businessunit, defaultpicture, email, firstname, function, isadmin, lastname, password, personnalidnumber) VALUES (nextval('hibernate_sequence'), 0, NULL, 'true', 'bengamra@viseo.com', 'Nihel', NULL, 'false', 'Ben Gamra', 123456, 'NIH7878');
INSERT INTO public.collaborator (id, version, businessunit, defaultpicture, email, firstname, function, isadmin, lastname, password, personnalidnumber) VALUES (nextval('hibernate_sequence'), 0, NULL, 'true', 'meng@viseo.com', 'Xiangzhe', NULL, 'false', 'Meng', 123456, 'XME7897');
INSERT INTO public.collaborator (id, version, businessunit, defaultpicture, email, firstname, function, isadmin, lastname, password, personnalidnumber) VALUES (nextval('hibernate_sequence'), 0, NULL, 'true', 'adli@viseo.com', 'Ouahib', NULL, 'false', 'Adli', 123456, 'MLI7888');
INSERT INTO public.collaborator (id, version, businessunit, defaultpicture, email, firstname, function, isadmin, lastname, password, personnalidnumber) VALUES (nextval('hibernate_sequence'), 0, NULL, 'true', 'lhote@viseo.com', 'Caroline', NULL, 'false', 'Lhote', 123456, 'CLK7787');
INSERT INTO public.collaborator (id, version, businessunit, defaultpicture, email, firstname, function, isadmin, lastname, password, personnalidnumber) VALUES (nextval('hibernate_sequence'), 0, NULL, 'true', 'benjamin.batista@viseo.com', 'Benjamin', NULL, 'false', 'Batista', 'bibimbaps', 'ABC1234');
INSERT INTO public.collaborator (id, version, businessunit, defaultpicture, email, firstname, function, isadmin, lastname, password, personnalidnumber) VALUES (nextval('hibernate_sequence'), 0, NULL, 'true', 'bourakkadi@viseo.com', 'Hamza', NULL, 'false', 'Bourakkadi', 123456, 'HAM7897');
INSERT INTO public.collaborator (id, version, businessunit, defaultpicture, email, firstname, function, isadmin, lastname, password, personnalidnumber) VALUES (nextval('hibernate_sequence'), 0, NULL, 'true', 'admin@viseo.com', 'Viseo', NULL, 'true', 'Admin', 'adminadmin', 'ADM1234');
INSERT INTO public.collaborator (id, version, businessunit, defaultpicture, email, firstname, function, isadmin, lastname, password, personnalidnumber) VALUES (nextval('hibernate_sequence'), 0, NULL, 'true', 'test1@test.com', 'Yuanhao', NULL, 'true', 'GU', 111111, 'TES1234');
INSERT INTO public.collaborator (id, version, businessunit, defaultpicture, email, firstname, function, isadmin, lastname, password, personnalidnumber) VALUES (nextval('hibernate_sequence'), 0, NULL, 'true', 'test2@test.com', 'Yuanhao', NULL, 'false', 'GU', 111111, 'TES1284');
ALTER SEQUENCE hibernate_sequence RESTART WITH 1;
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW(),  'JAVA');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'JAVASCRIPT');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'C');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'C++');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'SWIFT');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'HTML');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'PHP');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'CSS');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'VUE JS');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'HIBERNATE');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'AGILE');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'R');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'PYTHON');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'SYMFONY');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'SYMFONY 2');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'SQL');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'HSQL');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'POO');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'UML');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'SCRUM');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'MOBILE');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 2, NOW() ,  'ANDROID');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'BIG DATA');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'SPARK');
INSERT INTO public.skill (id, version, date, label) VALUES (nextval('hibernate_sequence'), 0, NOW() ,  'CONCEPTION');

INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 10, 17);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 9, 18);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 16, 14);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 23, 22);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 25, 18);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 9, 26);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 12, 26);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 11, 12);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 25, 24);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 19, 28);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 23, 15);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 22, 15);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 30, 29);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 13, 29);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 9, 30);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 20, 31);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 31, 21);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 32, 21);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 32, 31);
INSERT INTO public.link (id, version, skill1_id, skill2_id) VALUES (nextval('hibernate_sequence'), 0, 27, 33);

INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 9);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 10);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 11);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 12);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 2, 13);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 3, 13);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 4, 13);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 5, 13);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 6, 13);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 7, 13);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 13);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 2, 29);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 5, 29);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 6, 29);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 7, 29);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 29);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 14);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 5, 15);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 15);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 16);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 17);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 3, 18);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 18);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 3, 26);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 26);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 19);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 30);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 2, 20);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 3, 20);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 7, 20);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 20);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 1, 26);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 1, 30);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 1, 13);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 1, 11);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 1, 12);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 1, 10);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 1, 15);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 5, 1, 17);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 1, 20);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 3, 1, 19);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 5, 1, 14);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 3, 1, 16);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 2, 12);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 2, 10);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 3, 2, 11);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 2, 17);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 2, 9);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 2, 18);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 2, 16);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 2, 14);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 5, 2, 19);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 2, 2, 15);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 4, 11);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 4, 12);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 1, 4, 29);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 3, 4, 19);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 4, 20);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 4, 16);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 4, 14);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 5, 4, 9);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 3, 4, 18);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 3, 4, 26);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 4, 10);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 4, 17);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 4, 15);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 3, 11);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 3, 19);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 3, 30);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 3, 9);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 3, 29);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 3, 14);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 1, 3, 12);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 3, 15);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 4, 3, 16);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 3, 10);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 5, 18);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 3, 3, 17);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 4, 5, 17);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 5, 10);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 7, 9);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 3, 5, 9);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 5, 26);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 3, 7, 26);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 5, 12);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 5, 11);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 5, 5, 19);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 5, 5, 14);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 3, 5, 20);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'false', 3, 5, 16);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 7, 19);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 7, 10);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 4, 7, 18);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 7, 11);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 5, 7, 14);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 1, 7, 12);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 3, 7, 16);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 2, 7, 15);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 3, 7, 17);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 6, 9);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 4, 6, 17);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 6, 10);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 3, 6, 18);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 6, 11);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 6, 15);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 5, 6, 12);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'false', 3, 6, 26);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 5, 6, 20);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 6, 19);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 2, 6, 16);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 3, 6, 14);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 2, 21);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 3, 21);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 5, 21);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 21);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 1, 27);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 2, 27);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 3, 27);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 27);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 2, 22);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 5, 22);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 7, 22);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 22);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 2, 23);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 5, 23);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 7, 23);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 23);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 24);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 25);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 28);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 2, 31);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 3, 31);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 7, 31);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 31);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 1, 32);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 2, 32);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 3, 32);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 5, 32);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 7, 32);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 32);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 1, 33);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 2, 33);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 3, 33);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 5, 33);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 0, 'false', 0, 8, 33);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 1, 18);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 3, 22);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 4, 1, 9);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 1, 29);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 1, 23);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 1, 22);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 1, 31);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 5, 1, 28);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 2, 1, 21);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 1, 24);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'false', 2, 1, 25);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 2, 26);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 2, 30);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 3, 2, 28);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 2, 24);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 2, 25);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 5, 4, 28);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 4, 24);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 4, 25);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 4, 31);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 3, 23);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 4, 32);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 2, 4, 21);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 1, 4, 22);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 3, 4, 27);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 4, 33);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 3, 4, 30);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 4, 23);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 3, 28);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 3, 24);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 3, 25);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 4, 7, 33);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 5, 30);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 2, 5, 27);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 3, 5, 28);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 1, 5, 31);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 4, 5, 25);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 5, 24);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 7, 25);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 6, 30);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 1, 7, 30);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 1, 7, 21);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 7, 27);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 7, 24);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 2, 7, 28);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 6, 22);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 2, 6, 23);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'false', 3, 6, 31);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 4, 6, 21);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'false', 2, 6, 32);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 4, 6, 28);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 5, 6, 24);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 1, 'true', 5, 6, 27);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 4, 6, 25);
INSERT INTO public.expertise (id, version, isnoted, level, collaborator_id, skill_id) VALUES (nextval('hibernate_sequence'), 2, 'true', 3, 6, 33);

INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'REACT');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'Angular');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'spring');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'github');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'gitkraken');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'codeship');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'integration');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'jasmine');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'karma');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'test');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'junit');
INSERT INTO public.wish (id, version, label) VALUES (nextval('hibernate_sequence'), 0, 'git');
